### ISSUE TITLE
Ubuntu 20.10 support?

### ISSUE THREAD

**Issue by baqwas** [dalelane/node-red-contrib-plugin-asyncapi#15]
Hello!

Ran the install per doc; encountered the following messages:

`chowkidar@raspbari29:~/.node-red$ npm install node-red-contrib-plugin-asyncapi

> node-red-contrib-plugin-asyncapi@0.0.5 postinstall /home/chowkidar/.node-red/node_modules/node-red-contrib-plugin-asyncapi
> npm run getasyncapiparser && npm run getavroparser

> node-red-contrib-plugin-asyncapi@0.0.5 getasyncapiparser /home/chowkidar/.node-red/node_modules/node-red-contrib-plugin-asyncapi
> cp -v 'node_modules/@asyncapi/parser/dist/bundle.js' 'resources/asyncapi-parserjs-dist.js'

cp: cannot stat 'node_modules/@asyncapi/parser/dist/bundle.js': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-contrib-plugin-asyncapi@0.0.5 getasyncapiparser: `cp -v 'node_modules/@asyncapi/parser/dist/bundle.js' 'resources/asyncapi-parserjs-dist.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-contrib-plugin-asyncapi@0.0.5 getasyncapiparser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chowkidar/.npm/_logs/2021-04-15T02_55_12_799Z-debug.log
npm WARN twilio@3.54.2 requires a peer of @types/express@^4.17.7 but none is installed. You must install peer dependencies yourself.
npm WARN twilio@3.54.2 requires a peer of @types/qs@6.9.4 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-contrib-plugin-asyncapi@0.0.5 postinstall: `npm run getasyncapiparser && npm run getavroparser`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-contrib-plugin-asyncapi@0.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chowkidar/.npm/_logs/2021-04-15T02_55_13_821Z-debug.log
chowkidar@raspbari29:~/.node-red$ `

Probably a _self-inflicted newbie_ user/operator issue?
- @types/express@^4.17.7
- @types/qs@6.9.4

Don't want to guess for the above two packages; Twilio is installed. guidance would be appreciated. Thanks.

Kind regards.

**Comment by dalelane** [comment]
@baqwas Thanks so much for letting me know about this - I've published a new version that I hope will fix this for you

**Comment by baqwas** [comment]
Thanks for the fast turnaround. Rgds.
