### ISSUE TITLE
Work out how to use npm modules

### ISSUE THREAD

**Issue by dalelane** [dalelane/node-red-contrib-plugin-asyncapi#7]
The AsyncAPI parser code is embedded in the plugin which is horrible.

https://github.com/dalelane/node-red-contrib-plugin-asyncapi/blob/6b6182beebc3b182e4211834a7e1900d35aa77bb/asyncapi-plugin.html#L2-L4

I need to work out how to use npm modules in Node-RED plugins, so I can remove that.

**Comment by knolleary** [comment]
One short-term alternative is to add a build stage to your plugin that bundles your dependencies into the html. That isn't entirely satisfactory.

I'm looking at the plugin design to see how plugins can register additional content that should be exposed to the editor. That's fine if the plugin has a static directory of content to load - you have a slightly different requirement to include a file that is not part of the plugin directly, but comes from a dependency of your plugin. That gets a little tricker as we cannot assume where that file will be on disk... npm could have stuck it higher up in the node-path.
